import "@/styles/globals.css";
import "@/styles/grids.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import { GeistMono, GeistSans } from "geist/font";
import { headers } from "next/headers";

import { MainNav } from "@/components/nav/MainNav";
import { ThemeProvider } from "@/components/ThemeProvider";
import { env } from "@/env.mjs";
import { getUserSession } from "@/server/utils/userSession";
import { TRPCReactProvider } from "@/trpc/react";
import { api } from "@/trpc/server";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = getUserSession();
  const currentVersion = await api.turso.currentDBVersion.query();
  const latestVersion = await api.turso.latestDBVersion.query();
  return (
    <html lang="en">
      {/* eslint-disable-next-line @typescript-eslint/no-unsafe-member-access */}
      <body
        className={`${GeistSans.variable} ${GeistMono.variable}  font-sans`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TRPCReactProvider headers={headers()}>
            <div className="main-layout">
              <MainNav
                latestVersion={latestVersion}
                currentVersion={currentVersion}
                session={session}
              />
              {children}
            </div>
            {env.NODE_ENV === "development" && (
              <ReactQueryDevtools
                initialIsOpen={false}
                buttonPosition="bottom-left"
              />
            )}
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
