/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as EmployeesIdIndexRouteImport } from './routes/employees.$id.index'
import { Route as EmployeesIdTimeOffRouteImport } from './routes/employees.$id.time-off'
import { Route as EmployeesIdScheduleRouteImport } from './routes/employees.$id.schedule'

const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesIdIndexRoute = EmployeesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesIdRoute,
} as any)
const EmployeesIdTimeOffRoute = EmployeesIdTimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => EmployeesIdRoute,
} as any)
const EmployeesIdScheduleRoute = EmployeesIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => EmployeesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employees/$id': typeof EmployeesIdRouteWithChildren
  '/employees/': typeof EmployeesIndexRoute
  '/employees/$id/schedule': typeof EmployeesIdScheduleRoute
  '/employees/$id/time-off': typeof EmployeesIdTimeOffRoute
  '/employees/$id/': typeof EmployeesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesIndexRoute
  '/employees/$id/schedule': typeof EmployeesIdScheduleRoute
  '/employees/$id/time-off': typeof EmployeesIdTimeOffRoute
  '/employees/$id': typeof EmployeesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employees/$id': typeof EmployeesIdRouteWithChildren
  '/employees/': typeof EmployeesIndexRoute
  '/employees/$id/schedule': typeof EmployeesIdScheduleRoute
  '/employees/$id/time-off': typeof EmployeesIdTimeOffRoute
  '/employees/$id/': typeof EmployeesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/employees'
    | '/employees/$id'
    | '/employees/'
    | '/employees/$id/schedule'
    | '/employees/$id/time-off'
    | '/employees/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/employees'
    | '/employees/$id/schedule'
    | '/employees/$id/time-off'
    | '/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/employees'
    | '/employees/$id'
    | '/employees/'
    | '/employees/$id/schedule'
    | '/employees/$id/time-off'
    | '/employees/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/$id/': {
      id: '/employees/$id/'
      path: '/'
      fullPath: '/employees/$id/'
      preLoaderRoute: typeof EmployeesIdIndexRouteImport
      parentRoute: typeof EmployeesIdRoute
    }
    '/employees/$id/time-off': {
      id: '/employees/$id/time-off'
      path: '/time-off'
      fullPath: '/employees/$id/time-off'
      preLoaderRoute: typeof EmployeesIdTimeOffRouteImport
      parentRoute: typeof EmployeesIdRoute
    }
    '/employees/$id/schedule': {
      id: '/employees/$id/schedule'
      path: '/schedule'
      fullPath: '/employees/$id/schedule'
      preLoaderRoute: typeof EmployeesIdScheduleRouteImport
      parentRoute: typeof EmployeesIdRoute
    }
  }
}

interface EmployeesIdRouteChildren {
  EmployeesIdScheduleRoute: typeof EmployeesIdScheduleRoute
  EmployeesIdTimeOffRoute: typeof EmployeesIdTimeOffRoute
  EmployeesIdIndexRoute: typeof EmployeesIdIndexRoute
}

const EmployeesIdRouteChildren: EmployeesIdRouteChildren = {
  EmployeesIdScheduleRoute: EmployeesIdScheduleRoute,
  EmployeesIdTimeOffRoute: EmployeesIdTimeOffRoute,
  EmployeesIdIndexRoute: EmployeesIdIndexRoute,
}

const EmployeesIdRouteWithChildren = EmployeesIdRoute._addFileChildren(
  EmployeesIdRouteChildren,
)

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRouteWithChildren
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRouteWithChildren,
  EmployeesIndexRoute: EmployeesIndexRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
