/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayRollRouteImport } from './routes/pay-roll'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayRollIndexRouteImport } from './routes/pay-roll.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as PayRollIdRouteImport } from './routes/pay-roll.$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as DashboardWaitingOnRouteImport } from './routes/dashboard.waiting-on'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as EmployeesIdIndexRouteImport } from './routes/employees.$id.index'

const PayRollRoute = PayRollRouteImport.update({
  id: '/pay-roll',
  path: '/pay-roll',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRollIndexRoute = PayRollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayRollRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const PayRollIdRoute = PayRollIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PayRollRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)
const DashboardWaitingOnRoute = DashboardWaitingOnRouteImport.update({
  id: '/waiting-on',
  path: '/waiting-on',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const EmployeesIdIndexRoute = EmployeesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/pay-roll': typeof PayRollRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/waiting-on': typeof DashboardWaitingOnRoute
  '/employees/$id': typeof EmployeesIdRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/pay-roll/$id': typeof PayRollIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/pay-roll/': typeof PayRollIndexRoute
  '/employees/$id/': typeof EmployeesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/waiting-on': typeof DashboardWaitingOnRoute
  '/jobs/$id': typeof JobsIdRoute
  '/pay-roll/$id': typeof PayRollIdRoute
  '/customers': typeof CustomersIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/pay-roll': typeof PayRollIndexRoute
  '/employees/$id': typeof EmployeesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/pay-roll': typeof PayRollRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/waiting-on': typeof DashboardWaitingOnRoute
  '/employees/$id': typeof EmployeesIdRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/pay-roll/$id': typeof PayRollIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/pay-roll/': typeof PayRollIndexRoute
  '/employees/$id/': typeof EmployeesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/jobs'
    | '/pay-roll'
    | '/customers/$id'
    | '/dashboard/overview'
    | '/dashboard/projects'
    | '/dashboard/waiting-on'
    | '/employees/$id'
    | '/jobs/$id'
    | '/pay-roll/$id'
    | '/customers/'
    | '/employees/'
    | '/jobs/'
    | '/pay-roll/'
    | '/employees/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/customers/$id'
    | '/dashboard/overview'
    | '/dashboard/projects'
    | '/dashboard/waiting-on'
    | '/jobs/$id'
    | '/pay-roll/$id'
    | '/customers'
    | '/employees'
    | '/jobs'
    | '/pay-roll'
    | '/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/jobs'
    | '/pay-roll'
    | '/customers/$id'
    | '/dashboard/overview'
    | '/dashboard/projects'
    | '/dashboard/waiting-on'
    | '/employees/$id'
    | '/jobs/$id'
    | '/pay-roll/$id'
    | '/customers/'
    | '/employees/'
    | '/jobs/'
    | '/pay-roll/'
    | '/employees/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployeesRoute: typeof EmployeesRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  PayRollRoute: typeof PayRollRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pay-roll': {
      id: '/pay-roll'
      path: '/pay-roll'
      fullPath: '/pay-roll'
      preLoaderRoute: typeof PayRollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-roll/': {
      id: '/pay-roll/'
      path: '/'
      fullPath: '/pay-roll/'
      preLoaderRoute: typeof PayRollIndexRouteImport
      parentRoute: typeof PayRollRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/pay-roll/$id': {
      id: '/pay-roll/$id'
      path: '/$id'
      fullPath: '/pay-roll/$id'
      preLoaderRoute: typeof PayRollIdRouteImport
      parentRoute: typeof PayRollRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/dashboard/waiting-on': {
      id: '/dashboard/waiting-on'
      path: '/waiting-on'
      fullPath: '/dashboard/waiting-on'
      preLoaderRoute: typeof DashboardWaitingOnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/employees/$id/': {
      id: '/employees/$id/'
      path: '/'
      fullPath: '/employees/$id/'
      preLoaderRoute: typeof EmployeesIdIndexRouteImport
      parentRoute: typeof EmployeesIdRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardWaitingOnRoute: typeof DashboardWaitingOnRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardWaitingOnRoute: DashboardWaitingOnRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EmployeesIdRouteChildren {
  EmployeesIdIndexRoute: typeof EmployeesIdIndexRoute
}

const EmployeesIdRouteChildren: EmployeesIdRouteChildren = {
  EmployeesIdIndexRoute: EmployeesIdIndexRoute,
}

const EmployeesIdRouteWithChildren = EmployeesIdRoute._addFileChildren(
  EmployeesIdRouteChildren,
)

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRouteWithChildren
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRouteWithChildren,
  EmployeesIndexRoute: EmployeesIndexRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface PayRollRouteChildren {
  PayRollIdRoute: typeof PayRollIdRoute
  PayRollIndexRoute: typeof PayRollIndexRoute
}

const PayRollRouteChildren: PayRollRouteChildren = {
  PayRollIdRoute: PayRollIdRoute,
  PayRollIndexRoute: PayRollIndexRoute,
}

const PayRollRouteWithChildren =
  PayRollRoute._addFileChildren(PayRollRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  EmployeesRoute: EmployeesRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  PayRollRoute: PayRollRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
